#pragma once

#include "MessageIdentifiers.h"

namespace MessageIDs
{
	/*enum MessageIDs
	{
		ID_CONNECTION_INIT_LHMP = ID_USER_PACKET_ENUM + 1,
		ID_CONNECTION_REFUSED_LHMP,
		ID_CONNECTION_ACCEPTED_LHMP,
		
		ID_PACKET_LHMP,
		ID_SYNC_LHMP,
		ID_CREATE_PLAYER
	};

	enum LHMPSyncIDs
	{
		LHMP_PLAYER_ONFOOTSYNC
	};

	enum LHMPMessageIDs
	{
		LHMP_PLAYER_SPAWN,
	};

	enum RefusedMessageIDs
	{
		REFUSED_CLIENT_VERSION
	};*/

	enum MainCategoryIDs
	{
		LHMPID_CONNECTION = ID_USER_PACKET_ENUM + 1,
		LHMPID_SYNC,
		LHMPID_PLAYER,
	};

	enum ConnectionCategoryIDs
	{
		LHMPID_CONNECTION_INIT,
		LHMPID_CONNECTION_REFUSED,
		LHMPID_CONNECTION_ACCEPTED,
		LHMPID_CONNECTION_DISCONNECTED,
	};

	enum SyncCategoryIDs
	{
		LHMPID_SYNC_ONFOOT,
	};

	enum PlayerCategoryIDs
	{
		LHMPID_PLAYER_CREATE,
		LHMPID_PLAYER_CHATMSG,
		LHMPID_PLAYER_ONHIT,
		LHMPID_PLAYER_ONSHOOT,
		LHMPID_PLAYER_RESPAWN,
		LHMPID_PLAYER_WEAPON_ADD,
		LHMPID_PLAYER_WEAPON_REMOVE, 
		LHMPID_PLAYER_WEAPON_SWITCH,
		LHMPID_PLAYER_WEAPON_PICKUP,
		LHMPID_PLAYER_WEAPON_DROP
	};
};